// Nanit control protocol subset used by nanit-controller.
//
// Field numbers and enum values are based on the reverse-engineering work in
// Adam Staněk's nanit project and the later indiefan/home_assistant_nanit fork:
//   https://gitlab.com/adam.stanek/nanit
//   https://github.com/indiefan/home_assistant_nanit
//
// The original project states that its work is available under WTFPL v2.
// This repository owns and maintains this reduced schema; it intentionally
// excludes unrelated camera controls and sensor messages.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.0
// source: internal/protocol/nanit.proto

package nanitpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestType int32

const (
	RequestType_PUT_STREAMING RequestType = 2
)

// Enum value maps for RequestType.
var (
	RequestType_name = map[int32]string{
		2: "PUT_STREAMING",
	}
	RequestType_value = map[string]int32{
		"PUT_STREAMING": 2,
	}
)

func (x RequestType) Enum() *RequestType {
	p := new(RequestType)
	*p = x
	return p
}

func (x RequestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_protocol_nanit_proto_enumTypes[0].Descriptor()
}

func (RequestType) Type() protoreflect.EnumType {
	return &file_internal_protocol_nanit_proto_enumTypes[0]
}

func (x RequestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *RequestType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = RequestType(num)
	return nil
}

// Deprecated: Use RequestType.Descriptor instead.
func (RequestType) EnumDescriptor() ([]byte, []int) {
	return file_internal_protocol_nanit_proto_rawDescGZIP(), []int{0}
}

type StreamIdentifier int32

const (
	StreamIdentifier_MOBILE StreamIdentifier = 2
)

// Enum value maps for StreamIdentifier.
var (
	StreamIdentifier_name = map[int32]string{
		2: "MOBILE",
	}
	StreamIdentifier_value = map[string]int32{
		"MOBILE": 2,
	}
)

func (x StreamIdentifier) Enum() *StreamIdentifier {
	p := new(StreamIdentifier)
	*p = x
	return p
}

func (x StreamIdentifier) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamIdentifier) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_protocol_nanit_proto_enumTypes[1].Descriptor()
}

func (StreamIdentifier) Type() protoreflect.EnumType {
	return &file_internal_protocol_nanit_proto_enumTypes[1]
}

func (x StreamIdentifier) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *StreamIdentifier) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = StreamIdentifier(num)
	return nil
}

// Deprecated: Use StreamIdentifier.Descriptor instead.
func (StreamIdentifier) EnumDescriptor() ([]byte, []int) {
	return file_internal_protocol_nanit_proto_rawDescGZIP(), []int{1}
}

type Streaming_Status int32

const (
	Streaming_STARTED Streaming_Status = 0
	Streaming_STOPPED Streaming_Status = 1
)

// Enum value maps for Streaming_Status.
var (
	Streaming_Status_name = map[int32]string{
		0: "STARTED",
		1: "STOPPED",
	}
	Streaming_Status_value = map[string]int32{
		"STARTED": 0,
		"STOPPED": 1,
	}
)

func (x Streaming_Status) Enum() *Streaming_Status {
	p := new(Streaming_Status)
	*p = x
	return p
}

func (x Streaming_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Streaming_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_protocol_nanit_proto_enumTypes[2].Descriptor()
}

func (Streaming_Status) Type() protoreflect.EnumType {
	return &file_internal_protocol_nanit_proto_enumTypes[2]
}

func (x Streaming_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Streaming_Status) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Streaming_Status(num)
	return nil
}

// Deprecated: Use Streaming_Status.Descriptor instead.
func (Streaming_Status) EnumDescriptor() ([]byte, []int) {
	return file_internal_protocol_nanit_proto_rawDescGZIP(), []int{0, 0}
}

type Message_Type int32

const (
	Message_KEEPALIVE Message_Type = 0
	Message_REQUEST   Message_Type = 1
	Message_RESPONSE  Message_Type = 2
)

// Enum value maps for Message_Type.
var (
	Message_Type_name = map[int32]string{
		0: "KEEPALIVE",
		1: "REQUEST",
		2: "RESPONSE",
	}
	Message_Type_value = map[string]int32{
		"KEEPALIVE": 0,
		"REQUEST":   1,
		"RESPONSE":  2,
	}
)

func (x Message_Type) Enum() *Message_Type {
	p := new(Message_Type)
	*p = x
	return p
}

func (x Message_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Message_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_protocol_nanit_proto_enumTypes[3].Descriptor()
}

func (Message_Type) Type() protoreflect.EnumType {
	return &file_internal_protocol_nanit_proto_enumTypes[3]
}

func (x Message_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Message_Type) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Message_Type(num)
	return nil
}

// Deprecated: Use Message_Type.Descriptor instead.
func (Message_Type) EnumDescriptor() ([]byte, []int) {
	return file_internal_protocol_nanit_proto_rawDescGZIP(), []int{3, 0}
}

type Streaming struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       *StreamIdentifier `protobuf:"varint,1,req,name=id,enum=nanitpb.StreamIdentifier" json:"id,omitempty"`
	Status   *Streaming_Status `protobuf:"varint,2,req,name=status,enum=nanitpb.Streaming_Status" json:"status,omitempty"`
	RtmpUrl  *string           `protobuf:"bytes,3,req,name=rtmp_url,json=rtmpUrl" json:"rtmp_url,omitempty"`
	Attempts *int32            `protobuf:"varint,4,opt,name=attempts" json:"attempts,omitempty"`
}

func (x *Streaming) Reset() {
	*x = Streaming{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protocol_nanit_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Streaming) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Streaming) ProtoMessage() {}

func (x *Streaming) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_nanit_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Streaming.ProtoReflect.Descriptor instead.
func (*Streaming) Descriptor() ([]byte, []int) {
	return file_internal_protocol_nanit_proto_rawDescGZIP(), []int{0}
}

func (x *Streaming) GetId() StreamIdentifier {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return StreamIdentifier_MOBILE
}

func (x *Streaming) GetStatus() Streaming_Status {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return Streaming_STARTED
}

func (x *Streaming) GetRtmpUrl() string {
	if x != nil && x.RtmpUrl != nil {
		return *x.RtmpUrl
	}
	return ""
}

func (x *Streaming) GetAttempts() int32 {
	if x != nil && x.Attempts != nil {
		return *x.Attempts
	}
	return 0
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        *int32       `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Type      *RequestType `protobuf:"varint,2,req,name=type,enum=nanitpb.RequestType" json:"type,omitempty"`
	Streaming *Streaming   `protobuf:"bytes,4,opt,name=streaming" json:"streaming,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protocol_nanit_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_nanit_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_internal_protocol_nanit_proto_rawDescGZIP(), []int{1}
}

func (x *Request) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *Request) GetType() RequestType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return RequestType_PUT_STREAMING
}

func (x *Request) GetStreaming() *Streaming {
	if x != nil {
		return x.Streaming
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId     *int32       `protobuf:"varint,1,req,name=request_id,json=requestId" json:"request_id,omitempty"`
	RequestType   *RequestType `protobuf:"varint,2,req,name=request_type,json=requestType,enum=nanitpb.RequestType" json:"request_type,omitempty"`
	StatusCode    *int32       `protobuf:"varint,3,req,name=status_code,json=statusCode" json:"status_code,omitempty"`
	StatusMessage *string      `protobuf:"bytes,4,opt,name=status_message,json=statusMessage" json:"status_message,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protocol_nanit_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_nanit_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_internal_protocol_nanit_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetRequestId() int32 {
	if x != nil && x.RequestId != nil {
		return *x.RequestId
	}
	return 0
}

func (x *Response) GetRequestType() RequestType {
	if x != nil && x.RequestType != nil {
		return *x.RequestType
	}
	return RequestType_PUT_STREAMING
}

func (x *Response) GetStatusCode() int32 {
	if x != nil && x.StatusCode != nil {
		return *x.StatusCode
	}
	return 0
}

func (x *Response) GetStatusMessage() string {
	if x != nil && x.StatusMessage != nil {
		return *x.StatusMessage
	}
	return ""
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     *Message_Type `protobuf:"varint,1,req,name=type,enum=nanitpb.Message_Type" json:"type,omitempty"`
	Request  *Request      `protobuf:"bytes,2,opt,name=request" json:"request,omitempty"`
	Response *Response     `protobuf:"bytes,3,opt,name=response" json:"response,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_protocol_nanit_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_nanit_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_internal_protocol_nanit_proto_rawDescGZIP(), []int{3}
}

func (x *Message) GetType() Message_Type {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return Message_KEEPALIVE
}

func (x *Message) GetRequest() *Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *Message) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

var File_internal_protocol_nanit_proto protoreflect.FileDescriptor

var file_internal_protocol_nanit_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2f, 0x6e, 0x61, 0x6e, 0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x6e, 0x61, 0x6e, 0x69, 0x74, 0x70, 0x62, 0x22, 0xc4, 0x01, 0x0a, 0x09, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x12, 0x29, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02,
	0x28, 0x0e, 0x32, 0x19, 0x2e, 0x6e, 0x61, 0x6e, 0x69, 0x74, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x31, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x02, 0x28,
	0x0e, 0x32, 0x19, 0x2e, 0x6e, 0x61, 0x6e, 0x69, 0x74, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x69, 0x6e, 0x67, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x74, 0x6d, 0x70, 0x5f, 0x75, 0x72, 0x6c,
	0x18, 0x03, 0x20, 0x02, 0x28, 0x09, 0x52, 0x07, 0x72, 0x74, 0x6d, 0x70, 0x55, 0x72, 0x6c, 0x12,
	0x1a, 0x0a, 0x08, 0x61, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x61, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x73, 0x22, 0x22, 0x0a, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x54, 0x41, 0x52, 0x54, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x54, 0x4f, 0x50, 0x50, 0x45, 0x44, 0x10, 0x01, 0x22,
	0x75, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x28, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x6e, 0x61, 0x6e, 0x69, 0x74,
	0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x30, 0x0a, 0x09, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e,
	0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6e, 0x61, 0x6e, 0x69, 0x74, 0x70,
	0x62, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x52, 0x09, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x22, 0xaa, 0x01, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x49, 0x64, 0x12, 0x37, 0x0a, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x6e, 0x61, 0x6e, 0x69, 0x74,
	0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x02, 0x28, 0x05,
	0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x25, 0x0a, 0x0e,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x22, 0xc1, 0x01, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x29, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0e, 0x32, 0x15, 0x2e,
	0x6e, 0x61, 0x6e, 0x69, 0x74, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x2a, 0x0a, 0x07, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6e, 0x61,
	0x6e, 0x69, 0x74, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6e, 0x61, 0x6e, 0x69, 0x74,
	0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x30, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a,
	0x09, 0x4b, 0x45, 0x45, 0x50, 0x41, 0x4c, 0x49, 0x56, 0x45, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07,
	0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x45, 0x53,
	0x50, 0x4f, 0x4e, 0x53, 0x45, 0x10, 0x02, 0x2a, 0x20, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x11, 0x0a, 0x0d, 0x50, 0x55, 0x54, 0x5f, 0x53, 0x54,
	0x52, 0x45, 0x41, 0x4d, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x2a, 0x1e, 0x0a, 0x10, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x0a, 0x0a,
	0x06, 0x4d, 0x4f, 0x42, 0x49, 0x4c, 0x45, 0x10, 0x02, 0x42, 0x42, 0x5a, 0x40, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x65, 0x61, 0x74, 0x73, 0x66, 0x6f, 0x6e,
	0x61, 0x6d, 0x2f, 0x6e, 0x61, 0x6e, 0x69, 0x74, 0x2d, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x6c, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x6e, 0x61, 0x6e, 0x69, 0x74, 0x70, 0x62,
}

var (
	file_internal_protocol_nanit_proto_rawDescOnce sync.Once
	file_internal_protocol_nanit_proto_rawDescData = file_internal_protocol_nanit_proto_rawDesc
)

func file_internal_protocol_nanit_proto_rawDescGZIP() []byte {
	file_internal_protocol_nanit_proto_rawDescOnce.Do(func() {
		file_internal_protocol_nanit_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_protocol_nanit_proto_rawDescData)
	})
	return file_internal_protocol_nanit_proto_rawDescData
}

var file_internal_protocol_nanit_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_internal_protocol_nanit_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_protocol_nanit_proto_goTypes = []any{
	(RequestType)(0),      // 0: nanitpb.RequestType
	(StreamIdentifier)(0), // 1: nanitpb.StreamIdentifier
	(Streaming_Status)(0), // 2: nanitpb.Streaming.Status
	(Message_Type)(0),     // 3: nanitpb.Message.Type
	(*Streaming)(nil),     // 4: nanitpb.Streaming
	(*Request)(nil),       // 5: nanitpb.Request
	(*Response)(nil),      // 6: nanitpb.Response
	(*Message)(nil),       // 7: nanitpb.Message
}
var file_internal_protocol_nanit_proto_depIdxs = []int32{
	1, // 0: nanitpb.Streaming.id:type_name -> nanitpb.StreamIdentifier
	2, // 1: nanitpb.Streaming.status:type_name -> nanitpb.Streaming.Status
	0, // 2: nanitpb.Request.type:type_name -> nanitpb.RequestType
	4, // 3: nanitpb.Request.streaming:type_name -> nanitpb.Streaming
	0, // 4: nanitpb.Response.request_type:type_name -> nanitpb.RequestType
	3, // 5: nanitpb.Message.type:type_name -> nanitpb.Message.Type
	5, // 6: nanitpb.Message.request:type_name -> nanitpb.Request
	6, // 7: nanitpb.Message.response:type_name -> nanitpb.Response
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_internal_protocol_nanit_proto_init() }
func file_internal_protocol_nanit_proto_init() {
	if File_internal_protocol_nanit_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_protocol_nanit_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Streaming); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protocol_nanit_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protocol_nanit_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_protocol_nanit_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_protocol_nanit_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_protocol_nanit_proto_goTypes,
		DependencyIndexes: file_internal_protocol_nanit_proto_depIdxs,
		EnumInfos:         file_internal_protocol_nanit_proto_enumTypes,
		MessageInfos:      file_internal_protocol_nanit_proto_msgTypes,
	}.Build()
	File_internal_protocol_nanit_proto = out.File
	file_internal_protocol_nanit_proto_rawDesc = nil
	file_internal_protocol_nanit_proto_goTypes = nil
	file_internal_protocol_nanit_proto_depIdxs = nil
}
